title: Čistý vzduch 
baseURL: https://msvehlova.github.io/hugo-start/post/o-n%C3%A1s
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Kudy, kam, za čím a kdy vyrazit do přírody.
  authors: Authors

